-- 1. Create the table
create table public.measurements (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  bpm integer,
  device text
);

-- 2. Enable Row Level Security (Security best practice)
alter table public.measurements enable row level security;

-- 3. Create a policy to allow anyone (anon) to INSERT data
-- (Since we use the client-side anon key)
create policy "Allow Anon Insert"
on public.measurements
for insert
to anon
with check (true);

-- 4. Create a policy to allow reading (optional, for dashboard)
create policy "Allow Anon Read"
on public.measurements
for select
to anon
using (true);
