-- SCRIPT COMPLET v6.0 (Avec Session ID)
-- Copiez tout ce bloc et lancez-le dans Supabase SQL Editor.

-- 1. Création de la table (si elle n'existe pas déjà)
create table if not exists public.measurements (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  bpm integer,
  device text,
  session_id text
);

-- 2. Ajout des colonnes Data Science v4.0 (HRV, Strain)
alter table public.measurements add column if not exists hrv numeric;
alter table public.measurements add column if not exists strain numeric;

-- 3. Ajout colonne Pas v5.0 (Steps)
alter table public.measurements add column if not exists steps integer;

-- 4. Ajout colonne Session ID v6.0 (pour grouper les mesures)
alter table public.measurements add column if not exists session_id text;

-- 5. Index pour améliorer les performances
create index if not exists idx_measurements_session_id on public.measurements(session_id);
create index if not exists idx_measurements_created_at on public.measurements(created_at);

-- 6. Sécurité (Lecture/Ecriture pour tous)
alter table public.measurements enable row level security;
drop policy if exists "Allow Anon Insert" on public.measurements;
drop policy if exists "Allow Anon Read" on public.measurements;
create policy "Allow Anon Insert" on public.measurements for insert to anon with check (true);
create policy "Allow Anon Read" on public.measurements for select to anon using (true);
